apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: main
          image: docker-proxy.geekz.cn:81/nginx
          env:
            - name: TZ
              value: Asia/Shanghai
      restartPolicy: Always
  selector:
    matchLabels:
      app: nginx
